version: '3'
services:
  itsmweb :
    image : localhost/itsmng:1.5.1
    depends_on:
      - itsmdb
    container_name : itsmweb
    restart: always
    ports :
      - "8080:8080"
    volumes :
      - itsmng-config:/etc/itsm-ng
      - itsmng-plugins:/usr/share/itsm-ng/plugins
      - itsmng-files:/usr/share/itsm-ng/files
    environment:
      MARIADB_HOST : itsmdb
      MARIADB_USER : itsmng
      MARIADB_PASSWORD : itsmng
      MARIADB_DATABASE : itsmng
  itsmdb :
    image: docker.io/mariadb:10.6
    container_name: itsmdb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes :
      - itsmng-data:/var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "yes"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: iamastrongpassword
      MARIADB_USER : itsmng
      MARIADB_PASSWORD : itsmng
      MARIADB_DATABASE : itsmng

volumes:
  itsmng-config:
  itsmng-plugins:
  itsmng-files:
  itsmng-data:
